package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 15 de febrero de 2018 10H54' CET
*/

public interface HelloOperations 
{
  String msg ();
  void msg (String newMsg);
} // interface HelloOperations
